# Generated by Django 5.1.7 on 2025-03-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_important',
        ),
    ]
